### ISSUE TITLE
[Annex] Geodata-Verzeichnis aufräumen

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-kataster-dummy#1]
Zum jetzigen Zeitpunkt gibt es vier Dateien: https://geo.so.ch/geodata/ch.so.agi.extractannex.oereb/ Wahrscheinlich können alle bis auf `ch.so.agi.OeREB_extractAnnex.xtf` gelöscht werden. Diese Datei für Testzwecke plus minus aktuell halten, d.h. von Zeit zu Zeit wieder mal updaten.

**Comment by Luescher** [comment]
Nicht mehr aktuell. edit-DB ist der Master. Ordner wird gelöscht. Beim GRETL-Job annex könnte das xtf in den Ordner geschrieben werden, aber das geht glaube ich nicht wegen den Zonen.

**Comment by Luescher** [comment]
Hast du eine Idee wie man das xtf im Ornder https://geo.so.ch/geodata/ch.so.agi.extractannex.oereb/ aktuell halten kann?

**Comment by edigonzales** [comment]
@schmandr Wir haben sicher schon oft drüber diskutiert und die Meinung dazu sicher auch geändert ;) Falls GRETL-Jenkins von aussen greifbar, wären auch die Artefakte (o.ä.) verfügbar. So als Übergangslösung. Wenn die Datenabgabe da ist, löst sich das Problem, da GRETL sicher "in den neuen Datenabgabetopf" schreiben können muss.

**Comment by schmandr** [comment]
Resultat einer Besprechung mit  @edigonzales am Telefon:

Wir lassen den GRETL-Job so, wie er ist, und wir öffnen GRETL nicht gegen aussen. Andrea muss leider vorläufig "bei grösseren Änderungen" an den Annex-Daten die Datei unter geodata/ch.so.agi.extractannex.oereb/ manuell aktualisieren. Und wenn dann die Datenabgabe da ist, löst sich das Problem "von selbst".

Hm, kleiner Haken noch: Dieses .xtf wird gar nicht als Artefakt aufbewahrt. Andrea muss also den Export entweder manuell machen, oder wir müssen den GRETL-Job noch anpassen. Was aber bedeutet, dass wir ihm ein nochmal anderes Jenkinsfile geben müssen.

**Comment by Luescher** [comment]
Mache ich demnach periodisch von Hand, bis die Datenabgabe da ist.

**Comment by Luescher** [comment]
Ist nun wieder aktuell. Wird periodisch (manuell) mit ili2pg-4.3.1 exportiert.
