### ISSUE TITLE
Büsserach Wappen im Annexmodell falsch

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-kataster-dummy#10]
In Tabelle "agi_oereb_annex.oerb_xtnx_v1_0annex_logo" where acode=ch.2614 richtiges Wappen importieren
png 
![ch 2614](https://user-images.githubusercontent.com/3929984/72323976-3d5bfb80-36aa-11ea-8319-832ec82871dc.png)

oder
base64: 

`iVBORw0KGgoAAAANSUhEUgAAAWsAAAGYCAIAAAALIlSYAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wcLCjoixHuC1gAADYdJREFUeNrt3U1u3MoVgFE+SfuIHqypgYy0N68ge/PIgKYKrIXIcAYKDL3+YRfJ+rtV5yCDwM9uSVTz61skm/3Xl389LgDbvb79vLMVgN0UBFAQQEEABQFm8XDxT7//erBpgD+e79/NIIBVDKAggIIACgKgIICCAAoCKAiAggAKAigIoCAACgIoCKAggIIACgKgIICCAAoCKAiAggAKAigIoCCAggAoCKAggIIACgKgIICCAAoCKAigIAAKAigIoCCAggAoCKAggIIACgIoCICCAAoCKAigIAAKAigIoCCAggAKYhMACgIoCBDKg03QyvP9+8f/+f7LbwEFGWuvTrRj5z//Es/37+ePc/LXVAYFGaodKzv/ji9x8jgXKyMlKMiY6bm5V+/Lk7UPCqIv70UfWUdoy7mYkPmo+SVAQSLlY+s/FBEURD4gJKvoNa8vbyd/8vT10WYBBWk2gHxU6bxE6+d0Xl/eNsXr/HtwzBWrmB6nkpPddSUfry9vF/95enrW//n64zzfv1tbYQYJOXdcS8+Ox8n1fRpJMINMPfgcT4mRBAWZNwFZJhcdQUHmykfpGIGCBChCVyEwhqAgnUZk5W9+nFvJlRLrEZpwQD5DRA5eZvbnoS4+zqbErJ9LdkUJChKmJjuGi5OUZF/pXLuYLbFEzgSjIB0tcEo/SDlSwh+Og0wRqUJJcuQFBZl30hERFGTqiLg2hOasYwcZRg6eD9p0y2hQECkpuB7xURUKwggpubjM2XphyOeH3Xcm2LkbBSFwSvohJeNxJJU2KXESR0Ew11xetmwdSVAQgoWgkzWOiERnOWqgyHAD+owngx0rURBGS0nKwHJ8mjh5BClREEZIyfH1zsqZ4JQ6SImCEDUlXZESBQEpGYpzMQQeT5zKMYOM43ydf7KznfyFuO+szXgSJ0tELk4iW+NinDGDdN2U851tgA/xPn5dSaGLU3c8pnHGDNLXADLhuqaHtwWjIAyVkoNDSlcrJhSku8llyPuMlfihDt5onkIcByFwVlAQRASrGNgYkcrHNdbPrKMghEzJ+p6cOLO4RFVBMJJkGAocQ1UQZk8JsTiSCigIRhUDjoKAHMTiOAiBI+KkrBnECyOHNrtPIDeDEMPNG6D0OZXoi4LQYz6WLt8ZqBdWMcTIx83/hILgBRMUpFEOPv/JwLEwhszMcZB6M0XoWyvLBGYQDkXEmgsFIX9HlMUqBtac3DlZMjCDsCcfi+OmmEEoMZjYIGYQ2DmYoCAgKFjFMG6VrJXMILB/qHn6+mjYURCwJlIQ0BcUBFAQCqp//NIRUwWBoxHREQVh2JGkzu6tI/1zPQjdLStOjpWe3EVZUxQEiQkQMqxiqLE/V9uxP64oczZXQRgnIjXzcW2Zg4IACgIoCICCAAoCKAigIAAKAigI0Jz3xdAd739REFq69t5WsIphWz6WUd5F8rmDmmgGAasbBSH4eGKfxCqGPe0ABeFoRJQFBQEUBFAQQEEAFARQEEBBgAG5JpWyvM3PDAJ58rG4hk1BYHc+RERBoGBcUBB65OgDCoIxBAWh+rjRagB5fXkz+wzP2VxrlhrfjIlDQQiflcq78ecvd94R44mCED4i5Xbji7VSDQXBAgcUhLqevj5ayAzJuRiqdsRGUBAQFBQEUBBAQQAFARQEQEEABSGmk6vFXDymILAzIvIxMFe1U28S2fRfMYOAZJhBQEQwgwAKAigIoCCAggAoCKAggIIACgKgIICCAAoCKAiAggAKAigIoCDARNyjbGQnH23t/mCYQQAFARQEUBBmcXJYBBQEUBBAQQAFAVAQzriiDAUBFARQECxbmJx31okImEEAMwgDc6sBMwiAggAKAigIoCCAggAoCKAggIIACgKgIECFgjzfv9s05OWNMEN6eH37+fT4tw2BiGAVAygIoCDAGFYOjLrDUEGf76njEACDeX37aQZpUxOwigFQEEBBAAUBFARQEID9BfHmOsAMAhQuyMe1ZQBblyNmEMAqBqjoz8LFO+tKbmXvphtoXP/+y85iBoEDfXGCcltBbC+wUyQVxOkYLDDZwdKOStbvkFJ/l359edt305bn+/d5joncnLkcB6FGO27uqyl/xyTSywT3acmiILQcPY785VwR0RGrGCg1jLg9pVUMMQaQQHusMzKpBbGlMJ7YCEkFcUKXuJMLrUYtqxig2CoG4B/Lun8uVhQEKDmDOJgKWMUAGySODncrKxwAMwjsd/HU8rR3GzofMpIK4lAIkDSDWMgA6UODVQywcwmjIEDWVczxqQaYuiAOhcDMNo0LVjHAbdcGiw0FsZABzCCpcXRrGbjp4drE8vT4t60zjFz37FHVOV9NNxcE1Uh5TEGZxMrZlW0FmeqzdrRj0xdSE6sYtCPDl5aSeZYwawVxKEQ4pIT8M4iFjHYM8L2Rbv0SUy3QDti5hLlREAuZkdrx3//8++DX/fLth41PhhnEQiZQPo6H49pDCcoMA8jNd8kJgXwcDYqUmEE2L2SMIT23o2g4pGQeKW/TV4Fx8lE5HFIy/BImwwyyOJ4aIR/N23Hx+9GRGex/b643+8vHzW+s2++NLEsYqxjtqNERw8ioS5jUGcR9D+XDMEL+GcQZmSb5CLo3Ojgy3hJmcY8y+WjSkckn/5F+kNSCXGvSqMdTm7yvdPh8RPwpvMPYDGL6EBE2vPxvOu55V+77MJHKx+6fyDuPB5xBnJGRDxEZ/oVz625+Z2v2nI/hz4Nazkw0gxhD6udjho2w8mN2MoaMdzA11wCyZDySagzx4jxwRDznsxVksDGk4ZNgZd+YcLYPGpHJB5DF2Vz54MhCxhiypyDDXF12NcYuIjKGGEDMINYvIlJhDJncX79//965G1y57VCI99rtzkeWp9G1ncH65cO1d9/l2oc3xejzF732D6O8vzT7ALLMeX+QI9PH8Q9kk48jG/9IRPZNMSefDWw9lW0VE/RoSK5v7+nr48f/PIdqrmWO/LLKDS8hjgAW+iYnmkEKbcGPZ1Xia6MBpPIYIvG7R4HiM0igMeT5/r30t2Qe6W0MqfwbmWT0Prf/SOr/f0/Xb+Pew+GlJr/Xay+SBpCt9h1SbZXyno+nljiGmmEGWfq+RLXVy4JhpO0yZ7bnW9tv7OgM0ucYsnWTpUwBW2/wef46efHJbQDJNYaU+EjQHXd17XASKTeALFmOpPb2kVTp+di0937+yylPrJNjfgaTTuz7pce9QXTpySjDDNLVGJK4vbK88qc8q/5ExEGQvNv5ZAap8/kYiR3pZwxZ2R1yHX/IU5BOIlIzH4nPqvWCyEeWglS+yVugjhRdv2QuyNL6Oveb+Si3u6ZEREEKHQppdZemlI60jUiFAWSp8866CseoG+Zj8ZlsPR25qPlL7+GZ3zYfmQvS6sxu23zcHs1cbFZy2zb8pae8cvR2ijf7TnrXyU5e6JFrTgdbv5CxJXQ+0r9W/YjU/IqZC7JSuBI/1c18RJm3Cf1biPJ7L7FKuAvxXdqZCZ2tmkNB5ZGn6j3K8v5sK4/WMB/K1Xartv3Vr3z1Ojt2tQOoZQtSYS3TZz4wePYzHdRZGdx5DhlDGOO336RQpQpSdAzp/5ZQIjLzNm+ylqm/fik+g1Q+L2O/lQ/fzzgzSP1RLdZzSOymjVrlyxpKnxstW5D6Y0gUcd8tbgCJ8pq6VLm0ovgMkjciUQYQz2zqjCHNX4lrrGJmnkRExBZupc61nXeeQ/jVB/0O265fqhbEGKJ65H3a95CPqjOIo6rkDfHMFe5nl8l5j7IUR26GGOswKoV8+fYj3G/84qm3I3cw62QAWQY4DiIfhhEDSKt8NCiItQwMk482M4iIQPZ8tHJnG8EA+Wh1Z682BVn/aUUEQuSj5QwiIhA9H41XMSIC0TU+DiIiEHcAWXo4kioiEDQfy3j3SQX5mK4gR8YQt+pBPswgSRFp+0noIB9dr2IcEIFY+Vh6Ow4iIshHoHwsHR5J3bGNHApBPhSk9y0F+yS+wkXMx9Lt2dyt28sYQiwnpwWC5mPp+XoQkwgWL/3r+ooyEUE+Ot8Ler8mNX3zWcjQofWnZfR8LCGuahcRTB8KYjkDqfl4ffsZ5Tkf5p11iRvUGEKUJcwYr5eR3psrIgwv3Lh9Z/tCJwNIxKd3vPuDpGzlL99+mETw6qggljNMMYDEHa6j3qNMRJCPHtT+5O3sVj7K+zMftop8mEEMI8iHgogIjHJiMfwqZutyxoqG5gPISBcljPNpD94+g3yYQQwjyIeCiAjyMXo7Ri7IpojoCEYPBdER5ENBRAQrFwUJHREdweihIDqCfChI64joCNqhIEcjoiPaIR8KYhhBOxRER5APBbGoQTsUREd0RDtmpyBHOyIls7VDPhQkf0R0ZIZwaIeC6AjaoSA6QsV2yIeCNIiIlAwQDu1QEB3RDu1QECmhVji0Q0F0RDi0Q0FG74iU9BMO7VCQwB2Rkobh0A4FGacjUiIcCqIj2ahJ9mpoh4JM15GZU5L90wW1Q0GmTskMNSnxmaTCoSBSMmxNyn2MsXAoiJQMFZRqn3muHQqiI+GbUq0XwqEgUlLb8bjUD4RwKAjdpSQu4VAQ1EQ1FAQ1UQ0FQU1UAwVRE9VAQRg6K2KhIGiKXqAgEqMRHPA/isei1ttxk/gAAAAASUVORK5CYII=`

Bitte Befehl ins Ticket schreiben falls noch mehr Anpassuneg nötig sind. Merci

**Comment by barpasen** [comment]
UPDATE agi_oereb_annex.oerb_xtnx_v1_0annex_logo
SET
    logo = decode('base64StringOben', 'base64')
WHERE
    acode = 'ch.2614'

**Comment by Luescher** [comment]
Hat geklappt.
