### ISSUE TITLE
[Annex] Transparenz in Hintergrundkarte

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-kataster-dummy#2]
Die Hintergrundkarte ("nicht ausgefüllt") wird im PDF grau, dh. mit einer Transparenz dargestellt. Der Layer "ch.so.agi.grundbuchplan_oereb" muss analog der anderen "ausgefüllten" Hintergrundkarte im Annexmodell erfasst werden.

IST-Zustand:
![ist](https://user-images.githubusercontent.com/2767800/71725847-966b9a00-2e35-11ea-8d7a-b2401395c6ac.png)

SOLL-Zustand:
![soll](https://user-images.githubusercontent.com/2767800/71725858-9cfa1180-2e35-11ea-8276-24fecbf0f772.png)

**Comment by Luescher** [comment]
Ich hab da eigentlich 1.0 definiert. ist der Index -10 das Problem. Probiere es einmal
![hintergrund](https://user-images.githubusercontent.com/3929984/76875512-ebce1980-6870-11ea-8296-b35bd742b176.jpg)

**Comment by edigonzales** [comment]
Wahrscheinlich funktioniert es auf der Titelseite. Für die nachfolgenden "leere Hüsli"-Seiten, wird der spezielle GB-Plan verwendet:

https://github.com/sogis/oereb-web-service-docker/blob/master/Dockerfile

Siehe `  "--oereb.planForLandregister=https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.grundbuchplan_oereb&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=675&WIDTH=1920&HEIGHT=710&BBOX=2607051.2375,1228517.0374999999,2608067.2375,1228892.7458333333" \
`

Falls der im Annex fehlt, müsste dieser noch erfasst werden.

**Comment by Luescher** [comment]
grundbuchplan_oereb im Annex erfasst mit Transparenz 1.0
