### ISSUE TITLE
[Grundwasserschutz] URL-Hostname veraltet

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-kataster-dummy#6]
In den Ausgangsdaten "edit/afu_gewaesserschutz" wird für die Dokumenten-URL ein veralteter Hostname (geoweb.so.ch) verwendet. 

Es muss zwingend "geo.so.ch" verwendet werden!

Alt:
https://geoweb.so.ch/zonenplaene/Zonenplaene_pdf/7-Grenchen/Sonderbauvorschriften/7-332-S.pdf

Neu:
https://geo.so.ch/docs/ch.so.arp.zonenplaene/Zonenplaene_pdf//7-Grenchen/Sonderbauvorschriften/7-332-S.pdf

Auf der Integration-Edit-DB gibt es noch URLs "https://geoweb.so.ch/NULL". Auf der Prod-Umgebung ist mir das nicht aufgefallen. Daher wohl bereits gefixed (?).

**Comment by ojeker** [comment]
URL's auf Int und Prod gefixed.

/NULL auf Int stehen gelassen (Ist kein Problem - Prod Daten müssen stimmen)

**Comment by ojeker** [comment]
@Luescher : Falls dies noch vor dem golive prod gehen soll, muss der Job erneut angestossen werden. Bitte entscheiden und falls ja Peter zuweisen.

**Comment by Luescher** [comment]
"https://geoweb.so.ch/NULL" das ist ein Dummy-Wert in der Integrationsumgebung damit der GRETL-job durchläuft. Weil die Daten noch nicht alle ein Dokument hatten.

**Comment by schmandr** [comment]
> /NULL auf Int stehen gelassen (Ist kein Problem - Prod Daten müssen stimmen)

Ja, das ist OK in der Integrationsumgebung. Aber in den produktiven Daten sind immer noch 45 Dokumente mit textimweb NULL. Kannst du das auch noch beheben?

**Comment by schmandr** [comment]
Also: Gemäss Besprechung sollen die NULL-Werte bestehen bleiben dürfen. Dafür soll der GRETL-Job aber nur die Dokumente mit `rechtsstatus=inKraft` exportieren.
