### ISSUE TITLE
Einige PDF-Dokumente fehlen unter https://geo.so.ch/docs/ch.so.arp.zonenplaene/Zonenplaene_pdf

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-kataster-dummy#9]
In Tabelle `afu_gewaesserschutz.gwszonen_dokument` sind diverse Links auf Dokumente, die nicht funktionieren (die PDFs fehlen). Z.B.

https://geo.so.ch/docs/ch.so.arp.zonenplaene/Zonenplaene_pdf/83-Daeniken/Sonderbauvorschriften/83-98-S.pdf
https://geo.so.ch/docs/ch.so.arp.zonenplaene/Zonenplaene_pdf/112-Dornach/Sonderbauvorschriften/112-139-S.pdf
https://geo.so.ch/docs/ch.so.arp.zonenplaene/Zonenplaene_pdf/116-Metzerlen/Sonderbauvorschriften/116-44-S.pdf

**Comment by Luescher** [comment]
Diese Gemeinden sind noch nicht freigeschalten im ÖREB. Die Daten werden momentan erfasst. Deshalb okay.
